# Generated by Django 3.1.3 on 2020-11-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'person',
                'db_table': 'person',
                'unique_together': {('full_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=30)),
                ('date_of_release', models.DateField()),
                ('imbd_rating', models.FloatField(blank=True, null=True)),
                ('comic', models.CharField(max_length=10)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=15, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.person')),
            ],
            options={
                'verbose_name': 'movie_info',
                'verbose_name_plural': 'movie_info',
                'db_table': 'movie_info',
            },
        ),
    ]
