# Generated by Django 3.1.3 on 2020-11-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_created_person_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_info', to='movies.person')),
            ],
            options={
                'verbose_name': 'cast_info',
                'verbose_name_plural': 'cast_info',
                'db_table': 'cast_info',
            },
        ),
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=30)),
                ('date_of_release', models.DateField()),
                ('imbd_rating', models.FloatField(null=True)),
                ('comic', models.CharField(max_length=10)),
                ('cast', models.ManyToManyField(related_name='movie_info', through='movies.CastInformation', to='movies.Person')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.person')),
            ],
            options={
                'verbose_name': 'movie_info',
                'verbose_name_plural': 'movie_info',
                'db_table': 'movie_info',
            },
        ),
        migrations.AddField(
            model_name='castinformation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_info', to='movies.movieinformation'),
        ),
    ]
